import React from 'react';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faHome,
  faCalendarAlt,
  faUserFriends,
  faCog,
  faMoon,
  faSignOutAlt,
  faBullhorn,
  faReplyAll,
  faChevronDown,
  faClock,
  faArrowRight,
  faUserTie,
  faEllipsisH,
  faFileAlt,
  faExternalLinkAlt,
  faShareSquare,
  faSyncAlt,
  faAddressBook,
  faChartPie,
  faUserCircle,
  faBookReader,
  faBookOpen,
  faPaperPlane,
  faBug,
  faDownload,
  faPlay,
  faCalendarCheck,
  faShare,
  faUserAlt,
  faUser,
  faExclamationCircle,
  faComments,
  faLink,
  faCommentDots,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faHome,
  faComments,
  faExclamationCircle,
  faCalendarAlt,
  faUserFriends,
  faCog,
  faSyncAlt,
  faMoon,
  faSignOutAlt,
  faBullhorn,
  faReplyAll,
  faChevronDown,
  faClock,
  faArrowRight,
  faUserTie,
  faEllipsisH,
  faFileAlt,
  faExternalLinkAlt,
  faShareSquare,
  faAddressBook,
  faChartPie,
  faUserCircle,
  faBookReader,
  faBookOpen,
  faPaperPlane,
  faBug,
  faDownload,
  faPlay,
  faCalendarCheck,
  faShare,
  faUserAlt,
  faUser,
  faLink,
  faComments,
  faCommentDots,
);

const Icon = ({ name }) => {
  return <FontAwesomeIcon icon={name} />;
};

export default Icon;
